language: python
python:
  - "3.6"

dist: trusy
sudo: required

services:
  - docker

install:
  - docker-compose -f docker-compose.yml up -d
  - docker-compose exec web /bin/sh -c "cd/app;pip install -r requirements-dev"

script:
  - docker-compose exec web /bin/sh -c "cd/app;python -m pytest"

after_success:
  - docker-compose exec web /bin/sh -c "cd/app;codecov"
  - docker-compose down
